### PR TITLE
add challenge mirror, verify, format functionality

### PR DESCRIPTION
**Pull request by MilyMilo**
Adds `ctf challenge mirror <challenge>` and `ctf challenge verify <challenge>` adapted from #106 

Originally, this functionality was called `pull` and `verify` - however, `push` is already used to push challenge changes to the git repository. I think `mirror` is a better name, as ctfcli will attempt to mirror / copy the remote state from ctfd. This way  `pull` stays in its current git-like form, for git-related operations.

More additions:
- I've removed update / create / verify files - this can be achieved by just using --ignore=files.
- I've added `files_directory_name` (defaulting to `dist`) to specify where ctfcli should download the files, relative to challenge.yml
- I've added a warning when there are additional challenges on the remote, that are not registered locally
- `ctf challenge verify` will exit with status code 2 if the verification was successful, but some challenges are out of sync.
- I've fixed some typos

Thanks to @reteps for the initial contribution!

Closes: #101 #106

### CODE REVIEW

**Comment by MilyMilo** [comment]
Also I think we'll want to add `mirror` after performing the deploy, so that we can get the updated `connection_info`.

**Comment by reteps** [comment]
Hi there,

I have some additional changes on my fork you may want to port over. after a lot of testing with my college club. Good luck landing this!

**Comment by ColdHeat** [comment]
I like the choice of subcommands here. `mirror` and `verify` make sense. 

In terms of the deploy I think if we can mirror just the connection_info it would be best.

**Review by ColdHeat — APPROVED** [review]

**Comment by ColdHeat** [comment]
@MilyMilo This seems good to go. Is this still WIP or ready to merge?

**Comment by MilyMilo** [comment]
Yeah let's add the mirror after sync, I'll do that now.

**Comment by MilyMilo** [comment]
Okay so some more changes:

- `connection_info` will be added to the challenge.yml after deployment
- I've added a `challenge format` command to enforce the formatting used by ctfcli. It's pretty simple but running `mirror` will output challenge.yml files in that format, so if we want to be consistent we might as well format everything the same way.
- I've added the new commands to the README

**Pull request merged**
