### PR TITLE
Update challenge.py

### PR DESCRIPTION
**Pull request by whoo**
Due to changes regarding api in ctfd

### CODE REVIEW

**Comment by ColdHeat** [comment]
Hmmm is this actually the case? 

If you look at the demo CTFd instance (admittedly not updated to the current latest version), it refers to `challenge_id`. 
https://demo.ctfd.io/api/v1/hints (might need to login with `admin` and `password`)

**Comment by whoo** [comment]
Hi Guys,

Thanks for your work... (I didn't find other tool to configure ctfd via API like yours).

I've got an issue with
-- ctfd commit dc3a4d275bc3b60cf2a5a92364af76da9e1c4931
This patch fix my issue, If it's not relevant please delete.

Regards.


```
ctf challenge sync Shell/Samba/challenge.yml
Found Shell/Samba/challenge.yml
Loaded Ca bouge
Syncing Ca bouge
Traceback (most recent call last):
  File "/home/domi/.local/bin/ctf", line 8, in <module>
    sys.exit(main())
  File "/home/domi/.local/lib64/python3.6/site-packages/ctfcli/__main__.py", line 74, in main
    fire.Fire(CTFCLI)
  File "/home/domi/.local/lib64/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/domi/.local/lib64/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/domi/.local/lib64/python3.6/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/domi/.local/lib64/python3.6/site-packages/ctfcli/cli/challenges.py", line 134, in sync
    sync_challenge(challenge=challenge)
  File "/home/domi/.local/lib64/python3.6/site-packages/ctfcli/utils/challenge.py", line 105, in sync_challenge
    if hint["challenge_id"] == challenge_id:
KeyError: 'challenge_id'
```

**Comment by adam-lebon** [comment]
It should be great to accept this PR since the latest update now refers to `challenge`.
https://demo.ctfd.io/api/v1/hints :
```json
{"success": true, "data": [{"challenge": 4, "id": 1, "cost": 5, "type": "standard"}]}
```
I am facing this issue for several weeks.

Thanks in advance

**Comment by ColdHeat** [comment]
This should not have changed and it's really indicative of some other issue. I don't think merging this is the right idea. I think this is a CTFd issue.

**Comment by ColdHeat** [comment]
Actually I'm not so sure? I'm digging into this now and will push out a fix to the right area once I figure out what's going on.

**Comment by ColdHeat** [comment]
I see that this issue was introduced b/c of https://github.com/CTFd/CTFd/commit/ded612d46b4814ffcc62772e38e2a739992f2312. 

This looks to be some more nonsense that Marshmallow injects into the API. I'm going to push this as a fix in CTFd.

**Comment by ColdHeat** [comment]
@whoo @adam-lebon, please update your CTFd to latest master and it should resolve this issue. Merging this would be the wrong idea because it's actually challenge that shouldn't be there.

**Comment by whoo** [comment]
you're right this temporary fix shouldn't be used anymore.

**Pull request closed without merging**
