### PR TITLE
Add attribution field to challenge.yml spec

### PR DESCRIPTION
**Pull request by ColdHeat**
* Add attribution field to challenge.yml spec

### CODE REVIEW

**Comment by pl4nty** [comment]
is this different from the `author` field?

**Comment by ColdHeat** [comment]
@pl4nty Good question. Yes it will be different from the author field. Attribution will support markdown, mainly so that you can add links. 

image

I had added the author field so we could give people credit but I want to add the ability to link people's websites to their attribution line.

I think there is room for both of these since attribution is styled and author is unstyled.

**Comment by BobTheShoplifter** [comment]
The attribution field does not seem to want to publish when i try to add it to the file. Is it not added?

**Comment by ColdHeat** [comment]
Can you elaborate on what you’re trying and what you’re expecting?

**Comment by BobTheShoplifter** [comment]
Doing sync and install should fill the field attribution image

But currently it does not update or get filled from my testing

**Comment by BobTheShoplifter** [comment]
This is how it's in the file image

**Pull request merged**
